import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import TreeSvg from "../public/images/TreeSvg.svg";
import * as DropdownMenu from "@radix-ui/react-dropdown-menu";
import { HamburgerMenuIcon } from "@radix-ui/react-icons";
import stockTreeImage from "../public/images/stockTreeSurgeon.jpg";

const Home: NextPage = () => {
  return (
    <div className="flex min-h-screen flex-col items-center bg-[#eeeeee]">
      <Head>
        <title>ArbSOS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/TreeSvg.svg" />
      </Head>

      <header className="w-full flex px-2 justify-between bg-[#00ff8c]">
        <div className="flex">
          <TreeSvg className="w-12 h-12" />
          <h1 className="text-3xl p-2 font-semibold">ArbSOS</h1>
        </div>
        <DropdownMenu.Root>
          <DropdownMenu.Trigger>
            <HamburgerMenuIcon className="w-8 h-8 mr-1" />
          </DropdownMenu.Trigger>
          <DropdownMenu.Content className="border font-medium lg:text-xl rounded-md bg-[#00ff8c]">
            <DropdownMenu.Arrow
              className="fill-[#00ff8c] w-6 h-4 -mt-1"
              offset={10}
            ></DropdownMenu.Arrow>
            <DropdownMenu.Item className="p-2 lg:px-4">About</DropdownMenu.Item>
            <DropdownMenu.Item className="p-2 lg:px-4 border-t border-[#eeeeee]">
              Services
            </DropdownMenu.Item>
            <DropdownMenu.Item className="p-2 lg:px-4 border-t border-[#eeeeee]">
              Contact
            </DropdownMenu.Item>
          </DropdownMenu.Content>
        </DropdownMenu.Root>
      </header>

      <main className="w-full">
        <section className="w-full">
          <h1>Headline: Arboricultural Expert </h1>
          {/* <Image
            className=""
            src={stockTreeImage}
            alt="Jack and Elma"
            width={612}
            height={408}
            placeholder="blur"
            layout="responsive"
          /> */}
        </section>
        <section>Services</section>
      </main>
    </div>
  );
};

export default Home;
