import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import TreeSvg from "../public/TreeSvg.svg";
import * as DropdownMenu from "@radix-ui/react-dropdown-menu";
import { HamburgerMenuIcon } from "@radix-ui/react-icons";
import treeSurgeon from "../public/treeSurgeon.jpg";

const Home: NextPage = () => {
  return (
    <div className="flex min-h-screen flex-col items-center bg-dull">
      <Head>
        <title>ArbSOS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/TreeSvg.svg" />
      </Head>

      <header className="w-full flex px-2 justify-between bg-green">
        <div className="flex">
          <TreeSvg className="w-12 h-12" />
          <h1 className="text-3xl p-2 font-semibold">ArbSOS</h1>
        </div>
        <DropdownMenu.Root>
          <DropdownMenu.Trigger>
            <HamburgerMenuIcon className="w-8 h-8 mr-1" />
          </DropdownMenu.Trigger>
          <DropdownMenu.Content className="border">
            <DropdownMenu.Label>Hello</DropdownMenu.Label>
          </DropdownMenu.Content>
        </DropdownMenu.Root>
      </header>

      <main className="w-full flex flex-col">
        <div className="relative flex w-full h-full z-10">
          <Image
            src={treeSurgeon}
            alt={"tree surgeon"}
            placeholder="blur"
          ></Image>
          <div className="absolute inset-0 flex flex-col w-full text-center">
            <div className="flex items-center w-full justify-center my-[3%]">
              <TreeSvg className="w-16 h-16  md:w-32 md:h-32  fill-green" />
              <p className="text-green text-6xl md:text-9xl text-center">
                ArbSOS
              </p>
            </div>
            <p className="bg-dull/80 w-max mx-auto p-2 rounded-md z-50 text-black">
              Description and call to action
            </p>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
